exclude: 'helm|scripts|alembic'
default_stages: [commit]
fail_fast: true
default_language_version:
    python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.16
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args:
          - --line-length=120

#  - repo: https://github.com/timothycrosley/isort
#    rev: 5.13.2
#    hooks:
#      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject
          - flake8-print
          - flake8-eradicate
          - flake8-bugbear
          - flake8-simplify
          - flake8-comprehensions
          - flake8-variables-names
          - flake8-functions-names
